const labTests = [
  {
    name: "Alanine Aminotransferase (ALT; SGPT), Blood",
    lastValue: "14",
    date: "12/05/2021",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "unit/L",
    displayValue: "14 unit/L",
    resultCode: "1742-6",
    referenceRange: null,
    resultStatus: null,
  },
  {
    name: "Albumin, Blood",
    lastValue: "4.5",
    date: "12/05/2021",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "gm/dL",
    displayValue: "4.5 gm/dL",
    resultCode: "1751-7",
    referenceRange: "3.0 - 5.1 gm/dL",
    resultStatus: "NORMAL",
  },
  {
    name: "Alkaline phosphatase, Blood",
    lastValue: "135",
    date: "12/05/2021",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "unit/L",
    displayValue: "135 unit/L",
    resultCode: "6768-6",
    referenceRange: "50 - 130 unit/L",
    resultStatus: "HIGH",
  },
  {
    name: "Anion gap, Blood",
    lastValue: "8",
    date: "12/05/2021",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "mmol/L",
    displayValue: "8 mmol/L",
    resultCode: "33037-3",
    referenceRange: "7 - 14 mmol/L",
    resultStatus: "NORMAL",
  },
  {
    name: "Aspartate Aminotransferase (AST; SGOT), Blood",
    lastValue: "33",
    date: "12/05/2021",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "unit/L",
    displayValue: "33 unit/L",
    resultCode: "1920-8",
    referenceRange: "12 - 50 unit/L",
    resultStatus: "NORMAL",
  },
  {
    name: "Bilirubin, Blood",
    lastValue: "1.2",
    date: "12/05/2021",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "mg/dL",
    displayValue: "1.2 mg/dL",
    resultCode: "1975-2",
    referenceRange: "0.0 - 1.2 mg/dL",
    resultStatus: "NORMAL",
  },
  {
    name: "Bilirubin.direct, Blood",
    lastValue: "0.3",
    date: "12/05/2021",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "mg/dL",
    displayValue: "0.3 mg/dL",
    resultCode: "1968-7",
    referenceRange: "0.0 - 0.4 mg/dL",
    resultStatus: "NORMAL",
  },
  {
    name: "Bilirubin.indirect, Blood",
    lastValue: "0.9",
    date: "12/05/2021",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "mg/dL",
    displayValue: "0.9 mg/dL",
    resultCode: "1971-1",
    referenceRange: "0.0 - 1.2 mg/dL",
    resultStatus: "NORMAL",
  },
  {
    name: "Calcium, Blood",
    lastValue: "9.0",
    date: "12/05/2021",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "mg/dL",
    displayValue: "9.0 mg/dL",
    resultCode: "17861-6",
    referenceRange: "8.6 - 10.5 mg/dL",
    resultStatus: "NORMAL",
  },
  {
    name: "Carbon Dioxide (CO2), Blood",
    lastValue: "24",
    date: "12/05/2021",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "mmol/L",
    displayValue: "24 mmol/L",
    resultCode: "20565-8",
    referenceRange: "20 - 30 mmol/L",
    resultStatus: "NORMAL",
  },
  {
    name: "Chloride, Blood",
    lastValue: "109",
    date: "12/05/2021",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "mmol/L",
    displayValue: "109 mmol/L",
    resultCode: "2075-0",
    referenceRange: "99 - 112 mmol/L",
    resultStatus: "NORMAL",
  },
  {
    name: "Creatinine, Blood",
    lastValue: "0.70",
    date: "12/05/2021",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "mg/dL",
    displayValue: "0.70 mg/dL",
    resultCode: "2160-0",
    referenceRange: "0.35 - 1.13 mg/dL",
    resultStatus: "NORMAL",
  },
  {
    name: "Glucose, Blood",
    lastValue: "107",
    date: "12/05/2021",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "mg/dL",
    displayValue: "107 mg/dL",
    resultCode: "2345-7",
    referenceRange: "65 - 110 mg/dL",
    resultStatus: "NORMAL",
  },
  {
    name: "Potassium, Blood",
    lastValue: "3.7",
    date: "12/05/2021",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "mmol/L",
    displayValue: "3.7 mmol/L",
    resultCode: "6298-4",
    referenceRange: "3.5 - 5.2 mmol/L",
    resultStatus: "NORMAL",
  },
  {
    name: "Protein, Blood",
    lastValue: "7.6",
    date: "12/05/2021",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "gm/dL",
    displayValue: "7.6 gm/dL",
    resultCode: "2885-2",
    referenceRange: "6.5 - 8.3 gm/dL",
    resultStatus: "NORMAL",
  },
  {
    name: "Sodium, Blood",
    lastValue: "141",
    date: "12/05/2021",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "mmol/L",
    displayValue: "141 mmol/L",
    resultCode: "2951-2",
    referenceRange: "135 - 145 mmol/L",
    resultStatus: "NORMAL",
  },
  {
    name: "Urea Nitrogen (BUN), Blood",
    lastValue: "6",
    date: "12/05/2021",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "mg/dL",
    displayValue: "6 mg/dL",
    resultCode: "3094-0",
    referenceRange: "5 - 20 mg/dL",
    resultStatus: "NORMAL",
  },
  {
    name: "C Reactive Protein (CRP), Blood",
    lastValue: "3.1",
    date: "09/08/2021",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "mg/dL",
    displayValue: "3.1 mg/dL",
    resultCode: "1988-5",
    referenceRange: "0.0 - 1.0 mg/dL",
    resultStatus: "HIGH",
  },
  {
    name: "Lactate Dehydrogenase (LDH), Synovial fluid",
    lastValue: "2103",
    date: "09/08/2021",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "unit/L",
    displayValue: "2103 unit/L",
    resultCode: "68452-2",
    referenceRange: "313 - 618 unit/L",
    resultStatus: "HIGH",
  },
  {
    name: "Base excess, Venous Cord Blood",
    lastValue: "2.3",
    date: "07/13/2021",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "mmol/L",
    displayValue: "2.3 mmol/L",
    resultCode: "28639-3",
    referenceRange: null,
    resultStatus: null,
  },
  {
    name: "Bicarbonate, Venous Cord Blood",
    lastValue: "27",
    date: "07/13/2021",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "mmol/L",
    displayValue: "27 mmol/L",
    resultCode: "28641-9",
    referenceRange: "22 - 29 mmol/L",
    resultStatus: "NORMAL",
  },
  {
    name: "Carbon Dioxide (CO2), Blood",
    lastValue: "47.8",
    date: "07/13/2021",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "mmHg",
    displayValue: "47.8 mmHg",
    resultCode: "2021-4",
    referenceRange: "40.0 - 60.0 mmHg",
    resultStatus: "NORMAL",
  },
  {
    name: "Carbon Dioxide (CO2), Blood",
    lastValue: "28.8",
    date: "07/13/2021",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "mmol/L",
    displayValue: "28.8 mmol/L",
    resultCode: "2027-1",
    referenceRange: "23.0 - 30.0 mmol/L",
    resultStatus: "NORMAL",
  },
  {
    name: "Oxygen, Blood",
    lastValue: "43",
    date: "07/13/2021",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "mmHg",
    displayValue: "43 mmHg",
    resultCode: "2705-2",
    referenceRange: "26 - 55 mmHg",
    resultStatus: "NORMAL",
  },
  {
    name: "pH, Blood",
    lastValue: "7.38",
    date: "07/13/2021",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "-",
    displayValue: "7.38",
    resultCode: "2746-6",
    referenceRange: "7.31 - 7.41 -",
    resultStatus: "NORMAL",
  },
  {
    name: "Base excess, Blood",
    lastValue: "-1.4",
    date: "07/12/2021",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "mmol/L",
    displayValue: "-1.4 mmol/L",
    resultCode: "1925-7",
    referenceRange: null,
    resultStatus: null,
  },
  {
    name: "Bicarbonate, Blood",
    lastValue: "24",
    date: "07/12/2021",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "mmol/L",
    displayValue: "24 mmol/L",
    resultCode: "1960-4",
    referenceRange: "19 - 29 mmol/L",
    resultStatus: "NORMAL",
  },
  {
    name: "Carbon Dioxide (CO2), Blood",
    lastValue: "49.5",
    date: "07/12/2021",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "mmHg",
    displayValue: "49.5 mmHg",
    resultCode: "2019-8",
    referenceRange: "32.0 - 45.0 mmHg",
    resultStatus: "HIGH",
  },
  {
    name: "Carbon Dioxide (CO2), Blood",
    lastValue: "26",
    date: "07/12/2021",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "mmol/L",
    displayValue: "26 mmol/L",
    resultCode: "2026-3",
    referenceRange: "20 - 30 mmol/L",
    resultStatus: "NORMAL",
  },
  {
    name: "Galactose, Blood",
    lastValue: "78",
    date: "07/12/2021",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "mmHg",
    displayValue: "78 mmHg",
    resultCode: "2307-7",
    referenceRange: "80 - 105 mmHg",
    resultStatus: "LOW",
  },
  {
    name: "HbA1c/Total Hgb, Blood",
    lastValue: "TNP",
    date: "07/12/2021",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "-",
    displayValue: "TNP",
    resultCode: "4548-4",
    referenceRange: null,
    resultStatus: null,
  },
  {
    name: "pH, Venous Cord Blood",
    lastValue: "7.31",
    date: "07/12/2021",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "-",
    displayValue: "7.31",
    resultCode: "28647-6",
    referenceRange: "7.35 - 7.45 -",
    resultStatus: "LOW",
  },
  {
    name: "Albumin, Urine",
    lastValue: "26",
    date: "04/13/2021",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "mcg/mL",
    displayValue: "26 mcg/mL",
    resultCode: "1754-1",
    referenceRange: null,
    resultStatus: null,
  },
  {
    name: "Creatinine, Urine",
    lastValue: "221.7",
    date: "04/13/2021",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "mg/dL",
    displayValue: "221.7 mg/dL",
    resultCode: "2161-8",
    referenceRange: null,
    resultStatus: null,
  },
  {
    name: "Ferritin, Blood",
    lastValue: "1395",
    date: "03/03/2021",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "nanogram/mL",
    displayValue: "1395 nanogram/mL",
    resultCode: "2276-4",
    referenceRange: "27 - 265 nanogram/mL",
    resultStatus: "HIGH",
  },
  {
    name: "Cholesterol, Blood",
    lastValue: "103",
    date: "01/27/2021",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "mg/dL",
    displayValue: "103 mg/dL",
    resultCode: "2093-3",
    referenceRange: "107 - 200 mg/dL",
    resultStatus: "LOW",
  },
  {
    name: "HDL cholesterol, Blood",
    lastValue: "23",
    date: "01/27/2021",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "mg/dL",
    displayValue: "23 mg/dL",
    resultCode: "2085-9",
    referenceRange: "29 - 67 mg/dL",
    resultStatus: "LOW",
  },
  {
    name: "LDL cholesterol, Blood",
    lastValue: "43",
    date: "01/27/2021",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "mg/dL",
    displayValue: "43 mg/dL",
    resultCode: "13457-7",
    referenceRange: "65 - 120 mg/dL",
    resultStatus: "LOW",
  },
  {
    name: "Triglyceride, Blood",
    lastValue: "186",
    date: "01/27/2021",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "mg/dL",
    displayValue: "186 mg/dL",
    resultCode: "2571-8",
    referenceRange: "30 - 200 mg/dL",
    resultStatus: "NORMAL",
  },
  {
    name: "VLDL cholesterol, Blood",
    lastValue: "37",
    date: "01/27/2021",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "mg/dL",
    displayValue: "37 mg/dL",
    resultCode: "13458-5",
    referenceRange: "6 - 40 mg/dL",
    resultStatus: "NORMAL",
  },
  {
    name: "Vitamin D+Metabolites, Blood",
    lastValue: "28",
    date: "09/23/2020",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "nanogram/mL",
    displayValue: "28 nanogram/mL",
    resultCode: "35365-6",
    referenceRange: "30 - 80 nanogram/mL",
    resultStatus: "LOW",
  },
  {
    name: "Aldosterone, Blood",
    lastValue: "<4.0",
    date: "07/17/2020",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "nanogram/dL",
    displayValue: "<4.0 nanogram/dL",
    resultCode: "1763-2",
    referenceRange: null,
    resultStatus: null,
  },
  {
    name: "Glucose, Blood",
    lastValue: "97",
    date: "04/07/2020",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "mg/dL",
    displayValue: "97 mg/dL",
    resultCode: "2339-0",
    referenceRange: "65 - 110 mg/dL",
    resultStatus: "NORMAL",
  },
  {
    name: "Lipase, Blood",
    lastValue: "94",
    date: "12/05/2019",
    facilityName: "Children'S Mercy Hospital",
    testUnit: "unit/L",
    displayValue: "94 unit/L",
    resultCode: "3040-3",
    referenceRange: "23 - 300 unit/L",
    resultStatus: "NORMAL",
  },
];

export default labTests;
